---
title: "check_protein"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(parallel)
library(rlang)


### this is the code we used in https://pubmed.ncbi.nlm.nih.gov/35447093/
source('./get_triangulation_distances.R')
source('./iterate_triangulation_distance.R')
```


```{r}
pro = read.csv('../data/Pro_normed_counts&meta_final.csv')
pro$MS = as.character(pro$Overall.Molecular.Subtype..1...POLE..2...MMR..3...p53..4...NSMP..X...unknown)
length(unique(pro$phenoShort)) # 19 cell type version
fov_info = read.csv('../data/FOV_ann.csv')
colnames(fov_info) = c('tma_fov', 'BH_ann')
pro$tma_fov = paste0(pro$TMA.y, '_', pro$FOV_RNA)
pro = merge(x = pro, y = fov_info, by = "tma_fov", all.x = TRUE)

```

###### Bin all tumor cells here
```{r}
# Define tumor-related labels
tumor_labels <- c(
  "Carcinoma",
  "Spindle carcinoma vs sarcoma",
  "Sarcoma",
  "Rhabdomyosarcoma",
  "HG sarcoma vs PD carcinoma"
)

# Create a new column with binned values
pro$phenoBin <- ifelse(
  pro$phenoShort %in% tumor_labels,
  "Tumor",
  pro$phenoShort
)

table(pro$phenoBin)
```

```{r}
## add dummy global locations
pro['global_x'] = 0
pro['global_y'] = 0

i = 0
fovlist = unique(pro['TMA_FOV_RNA'])

for (fov in fovlist[[1]]){
  print(i)
  pro[pro['TMA_FOV_RNA'] == fov,'global_x']  = 10000*i + pro[pro['TMA_FOV_RNA'] == fov,'X_cent']
  pro[pro['TMA_FOV_RNA'] == fov,'global_y']  = 10000*i + pro[pro['TMA_FOV_RNA'] == fov,'Y_cent']
  i = i + 1
}
    
##
pro$data_index = c(1:nrow(pro))
cc2use = pro[,c('global_x', 'global_y', 'TMA_FOV_RNA', 'phenoBin', 'MS', 'data_index')]
cc2use['TMA_FOV_RNA-group'] = paste(cc2use$TMA_FOV_RNA, cc2use$MS, sep="-")

## run actual value
tri_dist_celltype <- get_triangulation_distances(df_input = cc2use,
                                                 id = "data_index",
                                                 x_pos = "global_x",
                                                 y_pos = "global_y",
                                                 cell_type = "phenoBin",
                                                 region = "TMA_FOV_RNA-group",
                                                 num_cores = 10)

tri_dist_iteration_celltype <- iterate_triangulation_distance(df_input = cc2use,
                                                                id = "data_index",
                                                                x_pos = "global_x",
                                                                y_pos = "global_y",
                                                                cell_type = "phenoBin",
                                                                region = "TMA_FOV_RNA-group",
                                                                num_iterations = 1000,
                                                                num_cores = 10,
                                                              threshold_pix = 512)

```

```{r}
## save out
write.csv(tri_dist_iteration_celltype, '../data/pro_tri_dist_iteration_celltypeV4.csv',
          row.names = FALSE)
write.csv(tri_dist_celltype, '../data/pro_tri_dist_celltypeV4.csv',
          row.names = FALSE)
```


########## no rerun just load

```{r}
tri_dist_iteration_celltype = read.csv('../data/pro_tri_dist_iteration_celltypeV4.csv')
tri_dist_celltype = read.csv('../data/pro_tri_dist_celltypeV4.csv')

## 180nm per pixel or say 0.18um
distance_threshold = 277 # corresponds to 50um or 100um

tri_dist_iteration_celltype$group = gsub(".*-", "", tri_dist_iteration_celltype$`TMA_FOV_RNA.group`)
tri_dist_celltype$group = gsub(".*-", "", tri_dist_celltype$`TMA_FOV_RNA.group`)

tri_dist_iteration_celltype$ms = 'Other'
tri_dist_iteration_celltype$ms[tri_dist_iteration_celltype$group == 2] = 'p53-WT'
tri_dist_iteration_celltype$ms[tri_dist_iteration_celltype$group == 3] = 'p53-ab'
tri_dist_iteration_celltype$ms[tri_dist_iteration_celltype$group == 4] = 'p53-WT'

tri_dist_celltype$ms = 'Other'
tri_dist_celltype$ms[tri_dist_celltype$group == 2] = 'p53-WT'
tri_dist_celltype$ms[tri_dist_celltype$group == 3] = 'p53-ab'
tri_dist_celltype$ms[tri_dist_celltype$group == 4] = 'p53-WT'


# Reformat observed dataset
ggdf_observed_celltype <- tri_dist_celltype %>%
  dplyr::filter(distance <= distance_threshold) %>%
  # Calculate observed mean distance and list values
  dplyr::group_by(celltype1, celltype2, ms) %>%
  summarize(observed = list(distance),
            observed_mean = mean(unlist(observed), na.rm = TRUE)) %>%
  ungroup()

# reformat iteration bg dataset
ggdf_expected_celltype <- tri_dist_iteration_celltype %>%
  gather(key = "iteration", value = "mean_distance", -c(celltype1, celltype2, `ms`))
ggdf_expected_celltype <- ggdf_expected_celltype %>% 
  mutate( group = `ms` ) %>%
  # Calculate expected mean distance and list values
  group_by(celltype1, celltype2, ms)
ggdf_expected_celltype$mean_distance = as.numeric(ggdf_expected_celltype$mean_distance) # NA exist but is taken care of 
ggdf_expected_celltype <- ggdf_expected_celltype %>%  
  summarize(expected = list(mean_distance),
            expected_mean = mean(mean_distance, na.rm = TRUE)) %>%
  ungroup() 
# Calculate pvalues
ggdf_pvals_celltypes <- ggdf_expected_celltype %>%
  left_join(ggdf_observed_celltype,
            by = c("celltype1", "celltype2", "ms")) %>%
  # Calculate wilcoxon test between observed and expected distances
  group_by(celltype1, celltype2, ms) %>%
  mutate(pvalue = wilcox.test(unlist(expected), unlist(observed), exact = FALSE)$p.value) %>%
  ungroup() %>%
  select(-observed, -expected)
# Calculate log fold enrichment
ggdf <- ggdf_pvals_celltypes %>%
  # Calculate log fold enrichment
  mutate(logfold_group = log2(observed_mean/expected_mean),
         interaction = paste0(celltype1, " --> ", celltype2))

# %>%
#  # Filter out pvalues less than 0.05
#  dplyr::filter(pvalue < 0.05)

### for visualization purpose, lets keep pvalue < 0.05; also keep M2 -> tumor borderline
a = subset(ggdf, ggdf$celltype2 == 'Tumor' & ggdf$celltype1 == 'M2' & ggdf$ms!='p53-WT')
b = subset(ggdf, ggdf$pvalue < 0.05)
ggdf1 = rbind(a,b)

ggdf2 = subset(ggdf1, ggdf1$celltype1 == "M2" | ggdf1$celltype2 == "M2")
```

############ M2 version, target grouping

```{r}
#ggdf2 = ggdf

# Assign cell type colors
ggdf3 <- ggdf2 %>%
  select(interaction, ms, logfold_group) %>%
  spread(key = ms, value = logfold_group) %>%
  mutate(diff = (`p53-WT` - `p53-ab`)) %>%
  arrange(`p53-ab`)
ord_diff = ggdf3$interaction

# Assign interaction order
ggdf2$interaction <- factor(ggdf2$interaction,
                            levels = ord_diff)

notake = c('Fibroblast desmoplastic stroma population', 'Benign stroma', 
           'Benign stroma vs perivascular smooth muscle','HG sarcoma vs PD carcinoma',
           'Other', 'Myometrium', 'Perivascular smooth muscle')
`%notin%` <- Negate(`%in%`)
ggdf2 = subset(ggdf2, ggdf2$celltype1 %notin% notake & ggdf2$celltype2 %notin% notake)

#### some clean up:
## remove inter that is not complete in either groups

ggdf2 = subset(ggdf2, ggdf2$interaction != 'Endothelial --> M2' & ggdf2$interaction != 'DC --> M2' & ggdf2$interaction != 'M2 --> Endothelial')

### make dumb bell plots

p = ggplot(data = ggdf2 %>%
         dplyr::filter(!is.na(interaction))) +
  #geom_vline(mapping = aes(xintercept = 0), linetype = "dashed") +
  geom_line(mapping = aes(x = logfold_group, y = interaction),
            na.rm = TRUE) +
  geom_point(mapping = aes(x = logfold_group, y = interaction, fill = ms), 
             size = 6, shape = 22, stroke = 0.5, alpha = 0.8, na.rm = TRUE) +
  scale_fill_manual(values=c("#6BA368", "#FF8C42")) +
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())
ggsave('../plot/inter_M2_abWT-p53_updated.svg', height = 4.5, width = 6)
p
```

